# UCS420 Cognitive Computing
## Assignment-4 — NumPy Introduction-1

Complete solutions for Q1–Q5 based on the uploaded assignment. fileciteturn0file0L5-L28

## Q1. NumPy 1-D Array and Basic Operations

In [ ]:
import numpy as np

# Create a NumPy 1-D array with 5 elements
arr = np.array([10, 20, 30, 40, 50])

print("Original array:", arr)

# a) Addition of 2 to all elements
print("After adding 2:", arr + 2)

# b) Multiply 3 with all elements
print("After multiplying by 3:", arr * 3)

# c) Divide every element by 2
print("After dividing by 2:", arr / 2)

## Q2(a). Reverse the NumPy Array

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 6, 4, 5])

print("Original array:", arr)
print("Reversed array:", arr[::-1])

## Q2(b). Find the Most Frequent Value and Its Indices

In [ ]:
import numpy as np

# i
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])

values, counts = np.unique(x, return_counts=True)
most_frequent = values[np.argmax(counts)]
indices = np.where(x == most_frequent)[0]

print("Array x:", x)
print("Most frequent value:", most_frequent)
print("Frequency:", counts[np.argmax(counts)])
print("Indices:", indices)

# ii
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

values, counts = np.unique(y, return_counts=True)
most_frequent = values[np.argmax(counts)]
indices = np.where(y == most_frequent)[0]

print("\nArray y:", y)
print("Most frequent value:", most_frequent)
print("Frequency:", counts[np.argmax(counts)])
print("Indices:", indices)

## Q3. Access Elements of a 2-D Array

In [ ]:
import numpy as np

arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

# a) Access 1st row, 2nd column
# Python uses zero-based indexing, so this is arr[0, 1]
print("1st row, 2nd column:", arr[0, 1])

# b) Access 3rd row, 1st column
# Python uses zero-based indexing, so this is arr[2, 0]
print("3rd row, 1st column:", arr[2, 0])

## Q4. 1-D Array Using linspace(), Properties, and Transpose

In [1]:
import numpy as np

# Create 25 evenly spaced numbers from 10 to 100
Rajat = np.linspace(10, 100, 25)

print("Array:")
print(Rajat)

# Dimensions
print("\nDimensions:", Rajat.ndim)

# Shape
print("Shape:", Rajat.shape)

# Total number of elements
print("Total elements:", Rajat.size)

# Data type of each element
print("Data type:", Rajat.dtype)

# Total number of bytes consumed
print("Total bytes:", Rajat.nbytes)

# Transpose using reshape()
transpose_Anmol = Rajat.reshape(1, 25)

print("\nTranspose using reshape():")
print(transpose_Anmol)

# T attribute
transpose_using_T = Rajat.T

print("\nUsing T attribute:")
print(transpose_using_T)

print("\nNote: Since Anmol is a 1-D array, T does not change its shape.")
print("To get a 2-D row/column transpose, first reshape the array.")

Array:
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]

Dimensions: 1
Shape: (25,)
Total elements: 25
Data type: float64
Total bytes: 200

Transpose using reshape():
[[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
   47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
   85.    88.75  92.5   96.25 100.  ]]

Using T attribute:
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]

Note: Since Anmol is a 1-D array, T does not change its shape.
To get a 2-D row/column transpose, first reshape the array.


## Q5. 2-D Array Operations, Reshape, and Resize

In [2]:
import numpy as np

# Create a 2-D array with 3 rows and 4 columns
ucs420_Rajat = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 15, 20, 35]
])

print("Original array ucs420_Rajat:")
print(ucs420_Rajat)

# Mean
print("\nMean:", np.mean(ucs420_Rajat))

# Median
print("Median:", np.median(ucs420_Rajat))

# Maximum
print("Maximum:", np.max(ucs420_Rajat))

# Minimum
print("Minimum:", np.min(ucs420_Rajat))

# Unique elements
print("Unique elements:", np.unique(ucs420_Rajat))

# Reshape to 4 rows and 3 columns
reshaped_ucs420_Rajat = ucs420_Rajat.reshape(4, 3)

print("\nReshaped array (4 x 3):")
print(reshaped_ucs420_Rajat)

# Resize to 2 rows and 3 columns
resized_ucs420_Rajat = np.resize(ucs420_Rajat, (2, 3))

print("\nResized array (2 x 3):")
print(resized_ucs420_Rajat)

Original array ucs420_Rajat:
[[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]

Mean: 43.333333333333336
Median: 37.5
Maximum: 90
Minimum: 10
Unique elements: [10 15 20 30 35 40 50 60 70 80 90]

Reshaped array (4 x 3):
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]

Resized array (2 x 3):
[[10 20 30]
 [40 50 60]]
